# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed3c71a40452d8dff425acf2a8e34f9a7c52ed7b9d227c85c6c12df58aedb27dc0be7245e21655b705be22345d9246cbafeac456fc7461b0f581f2799c63af7c

test:
  secret_key_base: 145cffde3f0d9b851057721577921eb5e96f9f4b2dd1a472d6e37ba2c56153281980cb1498fec0f4668f9a28a90aa4b8da856159f27686a2b249f9ece5d8f40f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
